### PR TITLE
Make all scripts executable

### PR DESCRIPTION
**Pull request by szepeviktor**
@greg-1-anderson

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
These scripts are designed to be run via `source`, so they do not need `+x`; in fact, I think not having the execute bit set is helpful, as it gives a clue to folks who try to run the script directly that it is not designed to be used this way.

**Comment by szepeviktor** [comment]
All right.

**Comment by szepeviktor** [comment]
Should shebang be removed? `#!/bin/bash`

**Comment by greg-1-anderson** [comment]
Maybe the shebang is deceptive. I thought it was helping my editor detect that it was a bash file, but syntax hiliting remains in effect if I remove it, so perhaps getting rid of it would be best.

**Pull request closed without merging**
