### PR TITLE
Add CI workflows

### PR DESCRIPTION
**Pull request by szepeviktor**
@greg-1-anderson 

1. EditorConfig keeps an eye on all your bytes
2. ShellCheck makes shell scripts robust

I hope you will like it.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Run these locally
- https://gitlab.com/greut/eclint/-/releases
- https://github.com/koalaman/shellcheck/releases

**Comment by greg-1-anderson** [comment]
I like it, and would merge it if it was passing, but I'm not sure why it's not running. Is this a chicken-and-egg problem, where I can't approve it to run because it's not enabled on the default branch, and this PR doesn't enable it because it's submitted from a fork?

**Comment by szepeviktor** [comment]
These need "some" work. (1000 ShellCheck problems)
See the PR in my fork: https://github.com/szepeviktor/greg-1-anderson_shell-scripts/pull/1/checks

I do not know why it does not start here.

**Comment by szepeviktor** [comment]
I could fix EC stuff.
Two-space indents everywhere? PHP too?

**Comment by greg-1-anderson** [comment]
I don't want to merge failing CI, so it would be helpful if you wanted to clean it up. Please give me a moment before you begin, though; I am going to relocate all of the backup / sync scripts to another repo, as I am not really using them right now & they are not well maintained. That will only take a moment.

Thank you for your contributions here. Are you using these scripts? Did you just notice this project when I created it, or were you a [utiliscripts](https://github.com/github/dmca/blob/master/2023/06/2023-06-14-ricoh.md) user?

**Comment by szepeviktor** [comment]
> Did you just notice this project when I created it

Yes, I have nothing to do for three years now.

**Comment by greg-1-anderson** [comment]
That sounds very rough. While I appreciate your help, I don't know how productive it is for you to contribute here. I recently made an effort to move things that other people would use to other projects (c.f. the things you linked to in the README); I am not sure that anyone other than me is going to be interested in what is here. I might suggest directing your efforts to:

- https://drupal.org
- https://github.com/consolidation

**Comment by szepeviktor** [comment]
Please do squash my commits.

**Comment by szepeviktor** [comment]
Review without whitespace changes: https://github.com/greg-1-anderson/shell-scripts/pull/1/files?diff=unified&w=1

**Comment by szepeviktor** [comment]
There is one more CI step invented lately.
```yaml
        -
            name: "Remove blank first lines and multiple blank lines"
            run: |
                git ls-files --cached -z | xargs --null -L 1 -- sed -i -e '/./,$!d' -e '/./n;N;/^\n$/D'
        -
            name: "Check differences to repository"
            run: "git diff --exit-code"
```

_(currently finds 27 lines)_

**Comment by szepeviktor** [comment]
I suppose introducing ShellCheck is equivalent to rewriting all scripts.

**Comment by greg-1-anderson** [comment]
It seems like the level of effort here is too high for the limited value of these scripts.

**Comment by szepeviktor** [comment]
You see!
You are a businessman. 👨🏻‍💼  I am a mad scientist. 😵

**Comment by greg-1-anderson** [comment]
> You are a businessman. 👨🏻‍💼 I am a mad scientist. 😵

Yes, perhaps you are right. I meant my statement to also cover the blank lines / whitespace changes; I feel bad for how much effort you would put in for the value. If you do want to push forward, I prefer [PSR-2 or PSR-12](https://github.com/consolidation/config/blob/main/composer.json#L47) for php code style checks. It would be okay to do the shell scripts and skip the php, but I'd still want a ✅ in your repo's workflow for whatever you do before merging.

**Comment by szepeviktor** [comment]
> skip the php,

Okay!

Doing just that ... 🏃🏻‍♂️

**Comment by szepeviktor** [comment]
Remaining PSR-12 problems
```
FILE: /home/viktor/src/Forks/greg-1-anderson_shell-scripts/save-macos-preferences.php
-------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 12 WARNINGS AFFECTING 12 LINES
-------------------------------------------------------------------------------------
 16 | WARNING | Line exceeds 120 characters; contains 134 characters
 17 | WARNING | Line exceeds 120 characters; contains 132 characters
 18 | WARNING | Line exceeds 120 characters; contains 123 characters
 19 | WARNING | Line exceeds 120 characters; contains 137 characters
 20 | WARNING | Line exceeds 120 characters; contains 123 characters
 28 | WARNING | Line exceeds 120 characters; contains 130 characters
 29 | WARNING | Line exceeds 120 characters; contains 131 characters
 32 | WARNING | Line exceeds 120 characters; contains 141 characters
 35 | WARNING | Line exceeds 120 characters; contains 135 characters
 36 | WARNING | Line exceeds 120 characters; contains 141 characters
 44 | WARNING | Line exceeds 120 characters; contains 138 characters
 46 | WARNING | Line exceeds 120 characters; contains 132 characters
-------------------------------------------------------------------------------------
```

**Comment by greg-1-anderson** [comment]
Hm I would prefer to disable that warning than figure out how to format those lines.

**Comment by greg-1-anderson** [comment]
Which is to say that I actively want to keep that formatting with one property per line.

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by greg-1-anderson** [comment]
Thanks for your efforts here.

**Comment by szepeviktor** [comment]
You're welcome.

Glad to meet your bytes.

**Pull request merged**
